name: bike_gps
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  country_picker: ^2.0.21
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  dropdown_button2: null
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_fonts: ^6.1.0
  image_stack: ^2.1.1
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  step_progress_indicator: ^1.0.2
  crypto:
  flutter_blue_plus: ^1.31.4
  flutter_barcode_scanner: ^2.0.0
  webview_flutter: ^4.2.2
  sign_in_with_apple: ^5.0.0
  purchases_flutter: ^6.18.0
  flutter_pdfview: ^1.2.7
  path_provider: ^2.1.2
  # packages for base project
  connectivity_plus: ^5.0.2
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.15.0
  firebase_core: ^2.14.0
  google_sign_in: ^6.1.4
  image_picker: null
  firebase_storage: null
  permission_handler: ^11.0.1
  geoflutterfire2: ^2.3.15
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  firebase_messaging: null
  get_storage: ^2.1.1
  intl: ^0.19.0
  url_launcher: null
  custom_map_markers: ^0.0.2+1
  timeago:
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.1.0
  # flutter_blue_plus: null
  fast_contacts: ^3.1.3
  fluttertoast:
  flutter_exit_app: ^1.1.2
  uuid:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito_sans/NunitoSans_10pt-Black.ttf
          weight: 900
    - family: DmSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/dm_sans/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/dm_sans/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/dm_sans/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/dm_sans/DMSans-Black.ttf
          weight: 900

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
